name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4

      - run: |
         sudo apt-get update -qq
         sudo apt-get install -qqq luarocks
      - name: Install pre-commit
        run: pip3 install pre-commit

      - name: Install LuaCheck
        run: luarocks install --local luacheck

      - name: Run LuaCheck using pre-commit
        run: |
         pre-commit run --all-files
         $HOME/.luarocks/bin/luacheck .
